### ISSUE TITLE
Simulator crash in _alter_constraints

### ISSUE THREAD

**Issue by sheogorath15** [DigitalPhonetics/adviser#19]
Simulator tires to remove value from list of possible values even though value is not in list while altering constraints
(simulator.py, line 504)

Traceback:
```
Traceback (most recent call last):
  File "adviser/services/service.py", line 497, in _receiver_thread
    func_instance(self, **values)
  File "adviser/services/service.py", line 557, in delegate
    result = func(self, *callargs, **kwargs)
  File "adviser/services/simulator/simulator.py", line 154, in user_turn
    self.receive(sys_act)
  File "adviser/services/simulator/simulator.py", line 192, in receive
    self.receive_options[sys_act.type](sys_act)
  File "adviser/services/simulator/simulator.py", line 279, in _receive_informbyalternatives
    self._receive_informbyname(sys_act)
  File "adviser/services/simulator/simulator.py", line 251, in _receive_informbyname
    if self._check_offer(offers, inform_list):
  File "adviser/services/simulator/simulator.py", line 617, in _check_offer
    altered_constraints = self._alter_constraints(informed_constraints_by_system, 1)
  File "adviser/services/simulator/simulator.py", line 504, in _alter_constraints
    possible_values.remove(_value)
ValueError: list.remove(x): x not in list
```

**Comment by mxschmdt** [comment]
What were the commands to run the simulation? (for reproduction)

**Comment by sheogorath15** [comment]
```python services/policy/rl/train_dqnpolicy.py -lf```

**Comment by mxschmdt** [comment]
The entry Dr. Emily Dinkinson in the ImsLecturers database had the department `na` but this is not reflected in the ontology thus it cannot be considered by the simulator. I changed her department to `phonetics`.

**Comment by mxschmdt** [comment]
Same problem still exists from slot position.
