### ISSUE TITLE
HTTP Error 401: Unauthorized while running the weather example.

### ISSUE THREAD

**Issue by tae898** [DigitalPhonetics/adviser#31]
```
(foo) ➜  adviser git:(master) ✗ python run_chat.py --tts --asr weather --cuda
/home/tk/.virtualenvs/foo/lib/python3.7/site-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))
To speak to the system, tap your right [CTRL] or [CMD] key.
It will try to automatically detect when your utterance is over.


recording...
System: Hi! What do you want to know about the weather?
>>> ...done recording.

/home/tk/.virtualenvs/foo/lib/python3.7/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /pytorch/aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
User: find what do you want to know about the weather

System: Which city are you at?

recording...
...done recording.

User: i live in amsterdam

System: For which day are you looking for the weather?

recording...
...done recording.

User: tomorrow

THREAD ERROR
Traceback (most recent call last):
  File "/home/tk/repos/adviser/adviser/services/service.py", line 499, in _receiver_thread
    func_instance(self, **values)
  File "/home/tk/repos/adviser/adviser/services/service.py", line 559, in delegate
    result = func(self, *callargs, **kwargs)
  File "/home/tk/repos/adviser/adviser/services/bst/bst.py", line 63, in update_bst
    num_entries, discriminable = self.bs.get_num_dbmatches()
  File "/home/tk/repos/adviser/adviser/utils/beliefstate.py", line 219, in get_num_dbmatches
    db_matches = self.domain.find_entities(constraints, self.domain.get_informable_slots())
  File "/home/tk/repos/adviser/adviser/examples/webapi/weather/domain.py", line 53, in find_entities
    forecast = self._query(constraints['location'], constraints['date'])
  File "/home/tk/repos/adviser/adviser/examples/webapi/weather/domain.py", line 135, in _query
    raise(e)
  File "/home/tk/repos/adviser/adviser/examples/webapi/weather/domain.py", line 131, in _query
    f = urlopen(url)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
```

**Comment by tae898** [comment]
The issue was the API key. haha. I got it fixed!
